export const reconciliationReasonCodes = {
    AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
    CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
    MULTIPLE_CANDIDATES: "MULTIPLE_CANDIDATES",
    EXACT_REFERENCE_MATCH: "EXACT_REFERENCE_MATCH",
    EXACT_AMOUNT_CURRENCY_DATE_MATCH:
        "EXACT_AMOUNT_CURRENCY_DATE_MATCH",
    DATE_WITHIN_TOLERANCE: "DATE_WITHIN_TOLERANCE",
    REFERENCE_MISMATCH: "REFERENCE_MISMATCH",
    INSUFFICIENT_EVIDENCE: "INSUFFICIENT_EVIDENCE",
} as const;

export type ReconciliationReasonCode =
    (typeof reconciliationReasonCodes)[keyof typeof reconciliationReasonCodes];